"""End-to-end UI regression in Chromium and iPhone-sized WebKit.

Uses the real HTTP service and Git DAG adapter; supplier/LLM responses are
deterministic fixtures so the test needs no distributor or LLM credentials.
"""
import json
import tempfile
import threading
from pathlib import Path
from unittest.mock import patch
from playwright.sync_api import sync_playwright, expect
from kosuzu.model import new_event
from kosuzu.server import make_server
from kosuzu.service import Service
from kosuzu.store import Store
from tests.helpers import FakeGitHub, part


def run(browser_type, mobile=False):
    with tempfile.TemporaryDirectory() as directory:
        store=Store(directory); upstream=FakeGitHub()
        service=Service(store,"server",upstream.factory)
        server=make_server(service,"127.0.0.1",0)
        thread=threading.Thread(target=server.serve_forever,daemon=True); thread.start()
        browser=browser_type.launch()
        context=browser.new_context(viewport={"width":390,"height":844} if mobile else {"width":1440,"height":1000},is_mobile=mobile,has_touch=mobile)
        page=context.new_page(); errors=[]; page.on("pageerror",lambda error:errors.append(str(error)))
        candidate=part(); candidate["package"]="0603"; candidate["category"]="Resistors"; candidate["review"]["confirmed"]=False
        try:
            page.goto(server.public_url)
            expect(page.locator("#login-form")).to_be_visible()
            page.locator("#access-key").fill(store.setting("admin_key")); page.locator("#login-form button").click()
            expect(page.locator("#setup-guide")).to_be_visible()
            expect(page.locator('#setup-progress [aria-current="step"]')).to_contain_text("GitHub connection")
            page.locator("#setup-next").click()
            expect(page.locator("#global-error")).to_contain_text("required GitHub tokens")
            page.locator("#setting-repo").fill("test/library")
            page.locator("#client-token").fill("client-test-token"); page.locator("#server-token").fill("server-test-token")
            page.locator("#setup-next").click()
            expect(page.locator('#setup-progress [aria-current="step"]')).to_contain_text("Suppliers")
            expect(page.locator("#client-token")).to_have_value("")
            page.reload()
            expect(page.locator('#setup-progress [aria-current="step"]')).to_contain_text("Suppliers")
            page.locator('[data-feature-supplier="mouser"][data-switch="enabled"]').uncheck()
            page.locator('[data-feature-supplier="arrow"][data-switch="use_api"]').uncheck()
            Path("test-results").mkdir(exist_ok=True)
            assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Setup has horizontal overflow"
            page.screenshot(path=f"test-results/{'mobile' if mobile else 'desktop'}-setup.png",full_page=True)
            page.locator("#setup-next").click()
            expect(page.locator('#setup-progress [aria-current="step"]')).to_contain_text("Review preferences")
            page.locator("#llm-enabled").uncheck()
            expect(page.locator("#llm-fields")).to_be_hidden()
            page.locator("#setup-next").click()
            expect(page.locator("#setup-ready")).to_be_visible()
            expect(page.locator("#setup-next")).to_be_disabled()
            upstream.offline=True
            page.locator("#check-connection").click()
            expect(page.locator("#global-error")).to_contain_text("Network unavailable")
            expect(page.locator("#setup-next")).to_be_disabled()
            upstream.offline=False
            page.locator("#setup-initialize").click()
            expect(page.locator("#connection-result")).to_contain_text("Database ready")
            page.locator("#check-connection").click()
            expect(page.locator("#connection-result")).to_contain_text("Connected to test/library")
            page.locator("#setup-next").click()
            expect(page.locator("#view-inventory")).to_be_visible()
            page.reload()
            expect(page.locator("#view-inventory")).to_be_visible()
            expect(page.locator("#setup-guide")).to_be_hidden()
            page.locator('[data-view="import"]').click()
            expect(page.locator('#supplier option[value="mouser"]')).to_have_count(0)
            page.locator("#supplier").select_option("lcsc"); page.locator("#supplier-code").fill("C25804")
            with patch("kosuzu.service.lookup",return_value=(candidate,"fixture supplier evidence")),patch("kosuzu.service.refine") as llm:
                page.locator("#lookup-button").click()
                expect(page.locator("#review-panel")).to_be_visible()
                expect(page.locator("#review-warnings")).to_contain_text("LLM review is disabled")
            llm.assert_not_called()
            page.locator("#discard-review").click()
            page.locator("#supplier").select_option("manual")
            page.locator("#manual-manufacturer").fill("Manual Components")
            page.locator("#manual-mpn").fill("M-123")
            page.locator("#manual-description").fill("Manually entered resistor")
            page.locator("#lookup-button").click()
            expect(page.locator("#review-panel")).to_be_visible()
            expect(page.locator("#review-warnings")).to_contain_text("No distributor lookup was performed")
            page.locator("#discard-review").click()
            page.locator('[data-view="settings"]').click()
            page.locator("#llm-enabled").check()
            page.locator("#llm-key").fill("llm-test-key"); page.locator("#llm-model").fill("test-model")
            page.get_by_role("button",name="Save settings",exact=True).click()
            expect(page.locator("#settings-saved")).to_have_text("Saved.")
            expect(page.locator("#client-token")).to_have_value("")
            page.locator('[data-view="import"]').click()
            page.locator("#supplier").select_option("lcsc"); page.locator("#supplier-code").fill("C25804")
            with patch("kosuzu.service.lookup",return_value=(candidate,"fixture supplier evidence")),patch("kosuzu.service.refine",return_value=candidate):
                page.locator("#lookup-button").click()
                expect(page.locator("#review-panel")).to_be_visible()
            page.locator("#part-location").fill("A2 / Drawer 6"); page.locator("#part-quantity").fill("50")
            page.locator("#part-confirmed").check(); page.locator('#review-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible()
            expect(page.locator("#request-list")).to_contain_text("pending")
            page.locator('[data-view="queue"]').click(); page.locator("#sync-server").click()
            expect(page.locator("#sync-info")).to_contain_text("Last completed sync")
            page.locator('[data-view="inventory"]').click(); page.locator("#refresh").click()
            expect(page.locator("#inventory-rows")).to_contain_text("R-10K")
            expect(page.locator("#stat-pieces")).to_have_text("50")
            page.locator("#search").fill("A2"); expect(page.locator("#result-count")).to_have_text("1 of 1 components")
            page.locator("#search").fill("no-such-part"); expect(page.locator("#inventory-empty")).to_be_visible()
            page.locator("#search").fill("")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-action").select_option("remove"); page.locator("#stock-quantity").fill("40")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible()
            page.locator('[data-view="queue"]').click(); page.locator("#sync-server").click()
            page.locator('[data-view="inventory"]').click(); page.locator("#refresh").click()
            expect(page.locator("#stat-pieces")).to_have_text("10")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-action").select_option("remove"); page.locator("#stock-quantity").fill("20")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible()
            page.locator('[data-view="queue"]').click(); page.locator("#sync-server").click()
            expect(page.locator("#error-list")).to_contain_text("Insufficient stock")
            expect(page.locator("#queue-count")).to_have_text("1")
            page.once("dialog",lambda dialog:dialog.accept())
            page.get_by_role("button",name="Reject request",exact=True).click()
            expect(page.locator("#error-list .status")).to_have_text("resolved")
            page.locator('[data-view="inventory"]').click()
            page.locator("#refresh").click(); expect(page.locator("#stat-pieces")).to_have_text("10")

            def sync_inventory():
                page.locator('[data-view="queue"]').click()
                with page.expect_response(lambda response:response.url.endswith('/api/sync')):
                    page.locator("#sync-server").click()
                expect(page.locator("#sync-server")).to_be_enabled()
                page.locator('[data-view="inventory"]').click()
                page.locator("#refresh").click()

            for name in ("BOXA","BOXB"):
                page.locator('[data-view="boxes"]').click(); page.locator("#new-box").click()
                page.locator("#box-name").fill(name)
                page.locator("#box-description").fill("Shelf 2 · "+name)
                page.locator("#box-image").fill("https://example.com/box.jpg")
                page.locator('#box-form button[type="submit"]').click()
                expect(page.locator("#view-requests")).to_be_visible()
                sync_inventory()
            boxes=service.github().inventory()["boxes"]
            box_a=next(id for id,b in boxes.items() if b["name"]=="BOXA")
            box_b=next(id for id,b in boxes.items() if b["name"]=="BOXB")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-action").select_option("transfer")
            page.locator("#stock-quantity").fill("10"); page.locator("#stock-to-box").select_option(box_a)
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#stat-pieces")).to_have_text("10")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-box").select_option(box_b); page.locator("#stock-quantity").fill("20")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#inventory-rows")).to_contain_text("BOXA: 10")
            expect(page.locator("#inventory-rows")).to_contain_text("BOXB: 20")
            expect(page.locator("#stat-pieces")).to_have_text("30")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            expect(page.locator("#stock-box-prompt")).to_be_visible()
            expect(page.locator("#stock-box")).to_have_value("")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#stock-dialog")).to_be_visible()
            page.locator("#stock-box").select_option(box_a); page.locator("#stock-quantity").fill("2")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#stat-pieces")).to_have_text("32")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-action").select_option("remove")
            expect(page.locator("#stock-box")).to_have_value("")
            page.locator("#stock-box").select_option(box_b); page.locator("#stock-quantity").fill("3")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#stat-pieces")).to_have_text("29")
            page.get_by_role("button",name="Adjust stock",exact=True).click()
            page.locator("#stock-action").select_option("remove")
            page.locator("#stock-box").select_option(box_a); page.locator("#stock-quantity").fill("13")
            page.locator('#stock-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#stat-pieces")).to_have_text("29")
            page.locator('[data-view="queue"]').click()
            expect(page.locator("#error-list")).to_contain_text("BOXA: available 12")
            page.once("dialog",lambda dialog:dialog.accept())
            page.get_by_role("button",name="Reject request",exact=True).click()
            expect(page.locator("#queue-count")).to_be_hidden()
            page.locator('[data-view="boxes"]').click()
            expect(page.locator("#box-list")).to_contain_text("Shelf 2 · BOXB")
            page.locator(f'[data-edit-box="{box_b}"]').click()
            page.locator("#box-description").fill("Updated box description")
            page.locator('#box-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            page.locator('[data-view="boxes"]').click()
            expect(page.locator("#box-list")).to_contain_text("Updated box description")
            page.screenshot(path=f"test-results/{'mobile' if mobile else 'desktop'}-boxes.png",full_page=True)
            page.locator(f'[data-box-contents="{box_a}"]').click()
            expect(page.locator("#box-filter")).to_have_value(box_a)
            expect(page.locator("#inventory-rows .stock-count")).to_have_text("12")
            page.locator("#box-filter").select_option("")
            page.locator('[data-view="settings"]').click(); page.locator("#llm-enabled").uncheck()
            page.get_by_role("button",name="Save settings",exact=True).click()
            expect(page.locator("#settings-saved")).to_have_text("Saved.")
            page.locator('[data-view="import"]').click(); page.locator("#supplier").select_option("adafruit")
            page.locator("#supplier-code").fill("3406")
            html='<script type="application/ld+json">'+json.dumps({"@type":"Product","sku":3406,"name":"Test board","image":"https://cdn-shop.adafruit.com/test.jpg"})+'</script>'
            with patch("kosuzu.suppliers.public_page",return_value=(html,"https://www.adafruit.com/product/3406")):
                page.locator("#lookup-button").click()
                expect(page.locator("#review-panel")).to_be_visible()
            expect(page.locator("#review-warnings")).to_contain_text("Catalog identity")
            page.locator("#part-box").select_option(box_b); page.locator("#part-quantity").fill("5")
            page.locator("#part-confirmed").check(); page.locator('#review-form button[type="submit"]').click()
            expect(page.locator("#view-requests")).to_be_visible(); sync_inventory()
            expect(page.locator("#inventory-rows")).to_contain_text("ADA-3406")
            expect(page.locator("#stat-pieces")).to_have_text("34")
            width=page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
            assert width, "Page has horizontal overflow"
            Path("test-results").mkdir(exist_ok=True)
            page.screenshot(path=f"test-results/{'mobile' if mobile else 'desktop'}-inventory.png",full_page=True)
            page.locator('[data-view="settings"]').click()
            expect(page.locator("#pages-settings")).to_be_visible()
            page.locator("#pages-enabled").check(); page.locator("#publish-pages").click()
            expect(page.locator("#pages-link")).to_have_attribute("href","https://test.github.io/library/")
            assert upstream.page_site["source"]=={"branch":"kosuzu-pages","path":"/"}
            exported=service.github().read("data.json",upstream.refs["kosuzu-pages"])
            assert sum(p["quantity"] for p in exported["parts"])==34
            page.locator("#unpublish-pages").click()
            expect(page.locator("#pages-status")).to_contain_text("unpublished")
            expect(page.locator("#pages-enabled")).not_to_be_checked()
            assert upstream.page_site is None
            manifest=page.request.get(server.public_url+"/manifest.webmanifest").json()
            assert manifest["display"]=="standalone"
            assert not errors,errors
            print(f"PASS {browser_type.name} {'mobile' if mobile else 'desktop'}: setup, manual/LLM/Adafruit import, box creation/edit/stock/filter/transfer, mandatory multi-box choice, overspend rejection, responsive layout")
        finally:
            context.close(); browser.close(); server.shutdown(); server.server_close(); store.db.close()


if __name__=="__main__":
    import argparse
    parser=argparse.ArgumentParser(); parser.add_argument("--chromium-only",action="store_true"); args=parser.parse_args()
    with sync_playwright() as playwright:
        run(playwright.chromium)
        if not args.chromium_only: run(playwright.webkit,mobile=True)
