'use strict';
const assert=require('node:assert/strict');
const search=require('../kosuzu/catalog_assets/search.js');
const make=(id,mpn,description,extra={})=>({id,mpn,description,manufacturer:'Example',supplier:'lcsc',supplier_code:'C'+id,category:'Resistors',package:'0603',location:'',attributes:{Resistance:'10 kohm'},quantity:10,boxes:{a:10},...extra});
const data={boxes:[{id:'a',name:'BOXA',description:'Workbench passives'}],parts:[make('1','R-10K','10 kohm precision resistor'),make('2','R-100K','100 kohm resistor'),make('3','ESP32-S3','WiFi microcontroller',{category:'Processors',attributes:{},quantity:0,boxes:{'':0}})]};
const rows=search.index(data);
assert.equal(search.search(rows,'r10k')[0].part.id,'1');
assert.equal(search.search(rows,'R-10K')[0].score,1000);
assert.equal(search.search(rows,'I want a 10 kohm resitsor')[0].part.id,'1');
assert.equal(search.search(rows,'microcontroler')[0].part.id,'3');
assert.equal(search.search(rows,'ESP32S3')[0].part.id,'3');
assert.equal(search.search(rows,'ESP32S2')[0].part.id,'3');
assert.equal(search.search(rows,'r10l')[0].part.id,'1');
assert.equal(search.search(rows,'C1')[0].part.id,'1');
assert.equal(search.search(rows,'BOXA').length,2);
assert.equal(search.search(rows,'Workbench').length,2);
assert.equal(search.search(rows,'nonsenseunrelated').length,0);
assert.equal(search.search(rows,'resistor',{category:'Processors'}).length,0);
assert.equal(search.search(rows,'',{box:'__unboxed__'})[0].part.id,'3');
assert.equal(search.search(rows,'',{stock:true}).length,2);
assert.equal(search.search(rows,'10 Ω')[0].part.id,'1');
assert.equal(search.distance('resitsor','resistor',1),1);
assert.equal(search.distance('aaaa','bbbb',1),2);
const large=search.index({...data,parts:Array.from({length:10000},(_,i)=>make(String(i),'R-'+i,'precision resistor'))});
const started=performance.now(); search.search(large,'I need a precision resitsor');
const elapsed=performance.now()-started;
assert.ok(elapsed<4000,`10k-part fuzzy search took ${elapsed}ms`);
console.log(`Catalog search: PASS (10k parts, ${Math.round(elapsed)}ms)`);
